joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

camera_controller:
  type: "position_controllers/JointPositionController"
  joint: camera_link

right_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: right_wheel_hinge

left_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: left_wheel_hinge
